Repository ipt-cryptolabs/fi-labs-2023, pull requests merged in 2023-06, with the labels that each got.

#44 [CP-3] Pochynok Fi-03
  cp_3/pochynok_fi-03/.keep
  cp_3/pochynok_fi-03/15.txt
  cp_3/pochynok_fi-03/3.ipynb
  cp_3/pochynok_fi-03/Протокол_крипта3.pdf
Labels: needs cleanup

#16 [CP-1] Antonenko (FI-03), Kistaiev (FI-03)
  cp_1/antonenko_kistaiev_fi-03/README.md
  cp_1/antonenko_kistaiev_fi-03/bigram frequencies excel.xlsx
  cp_1/antonenko_kistaiev_fi-03/bigram frequencies.pdf
  cp_1/antonenko_kistaiev_fi-03/char frequencies excel.xlsx
  cp_1/antonenko_kistaiev_fi-03/char frequencies.pdf
  cp_1/antonenko_kistaiev_fi-03/girkin.txt
  cp_1/antonenko_kistaiev_fi-03/kripta.mlx
  cp_1/antonenko_kistaiev_fi-03/kripta.pdf
  cp_1/antonenko_kistaiev_fi-03/laba.html
Labels: incomplete results

#43 [CP-2] Pochynok FI-03
  cp_2/pochynok_fi_03/2.ipynb
  cp_2/pochynok_fi_03/dec.txt
  cp_2/pochynok_fi_03/text.txt
  cp_2/pochynok_fi_03/Протокол_крипта2.docx
  cp_2/pochynok_fi_03/Протокол_крипта2.pdf
Labels: incomplete results, question

#45 [CP-4] Babych (FI-04)
  cp_4/babych_fi-04/__pycache__/lrz.cpython-311.pyc
  cp_4/babych_fi-04/__pycache__/variant.cpython-311.pyc
  cp_4/babych_fi-04/calculations.py
  cp_4/babych_fi-04/constants.py
  cp_4/babych_fi-04/lrz.py
  cp_4/babych_fi-04/results.py
  cp_4/babych_fi-04/variant.py
  cp_4/babych_fi-04/Сим крипта лаб-4.pdf
Labels: bad results
