Repository ipt-cryptolabs/fi-labs-2023, pull requests merged in 2023-05, with the labels that each got.

#1 [CP-1] Burzhymskyi (FI-03), Nedozhdii (FI-03)
  cp_1/burzhymskyi_fi-03_nedozhdii_fi-03_cp1/CMakeLists.txt
  cp_1/burzhymskyi_fi-03_nedozhdii_fi-03_cp1/lab1.pdf
  cp_1/burzhymskyi_fi-03_nedozhdii_fi-03_cp1/main.cpp
  cp_1/burzhymskyi_fi-03_nedozhdii_fi-03_cp1/text/text1.txt
Labels: report improvements, incomplete results

#20 [CP-2] Babych (FI-04)
  cp_2/babych_fi-04/clear_text1.txt
  cp_2/babych_fi-04/lab2.py
  cp_2/babych_fi-04/text.txt
  cp_2/babych_fi-04/text_1v.txt
  cp_2/babych_fi-04/сим крипта лаб-2.pdf
Labels: needs cleanup

#36 [CP-1] Koval, Nedashkivskyi (FI-04)
  cp_1/koval_nedashkivskyi_fi-04/cp1.ipynb
  cp_1/koval_nedashkivskyi_fi-04/images/image_2023-04-10_19-37-44.png
  cp_1/koval_nedashkivskyi_fi-04/images/image_2023-04-10_19-41-10.png
  cp_1/koval_nedashkivskyi_fi-04/images/image_2023-04-10_19-41-37.png
  cp_1/koval_nedashkivskyi_fi-04/images/image_2023-04-10_19-42-33.png
  cp_1/koval_nedashkivskyi_fi-04/krasa_ruskava_yazika.txt
  cp_1/koval_nedashkivskyi_fi-04/КП1_Коваль_Недашківський_ФІ04.pdf
Labels: bad results
